const BOOK_LIST_ACTIONS = Object.freeze({
  FETCH_BOOKS_SUCCESS: "FETCH_BOOKS_SUCCESS",
  FETCH_BOOKS_REQUEST: "FETCH_BOOKS_REQUEST",
  FETCH_BOOKS_FAILURE: "FETCH_BOOKS_FAILURE",
})

const SHOPPING_CART_ACTIONS = Object.freeze({
  BOOK_ADDED_TO_CART: "BOOK_ADDED_TO_CART",
  BOOK_REMOVED_FROM_CART: "BOOK_REMOVED_FROM_CART",
  ALL_BOOK_REMOVED_FROM_CART: "ALL_BOOK_REMOVED_FROM_CART",
})

export { BOOK_LIST_ACTIONS, SHOPPING_CART_ACTIONS }
